/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        midnight: 'var(--midnight)',
        ink: 'var(--ink)',
        paper: 'var(--paper)',
        surface: '#f9f9ff',
        muted: 'var(--muted)',
        line: 'var(--line)',
        primary: '#00272c',
        secondary: '#815600',
        accent: 'var(--accent)',
        
        // Custom EduSync / ShikshaSetu Premium Colors
        'deep-teal': '#1F4E5F',
        marigold: '#E8A33D',
        sage: '#6B9080',
        'warm-clay': '#C1502E',

        // Uploaded Landing Theme Colors
        "on-primary-fixed-variant": "#2a4c51",
        "surface-tint": "#426469",
        "error-container": "#ffdad6",
        "primary-container": "#1a3d42",
        "error": "#ba1a1a",
        "tertiary-container": "#323a3a",
        "surface-bright": "#f9f9ff",
        "tertiary-fixed": "#dce4e4",
        "inverse-on-surface": "#ebf1ff",
        "on-secondary-fixed-variant": "#624000",
        "outline-variant": "#c1c8c9",
        "on-secondary": "#ffffff",
        "on-surface": "#111c2c",
        "primary-fixed-dim": "#a9cdd3",
        "on-surface-variant": "#414849",
        "surface-container-highest": "#d8e3fa",
        "on-tertiary-fixed-variant": "#404849",
        "on-secondary-fixed": "#291800",
        "on-error": "#ffffff",
        "primary-fixed": "#c5e9ef",
        "inverse-surface": "#263142",
        "surface-dim": "#cfdaf1",
        "secondary-container": "#fcba52",
        "on-primary-container": "#85a7ad",
        "on-background": "#111c2c",
        "surface-container-lowest": "#ffffff",
        "background": "#f9f9ff",
        "tertiary-fixed-dim": "#c0c8c8",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#a9cdd3",
        "tertiary": "#1d2425",
        "secondary-fixed-dim": "#fcba52",
        "on-secondary-container": "#714b00",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#9ba4a4",
        "surface-container-high": "#dee8ff",
        "on-tertiary-fixed": "#151d1d",
        "surface-variant": "#d8e3fa",
        "secondary-fixed": "#ffddb1",
        "surface-container-low": "#f0f3ff",
        "on-primary-fixed": "#001f24",
        "on-error-container": "#93000a",
        "surface-container": "#e7eeff",
        "outline": "#717879"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1280px",
        "unit": "8px",
        "gutter": "24px",
        "section-gap": "80px"
      },
      fontFamily: {
        display: ['Manrope', '"Space Grotesk"', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'monospace'],
        serif: ['"Source Serif 4"', 'serif'],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "title-md": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "title-md": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
