import { StudentRecord } from './types';

export const STUDENTS_DATA: StudentRecord[] = [
  {
    id: 'std-001',
    name: 'Aarav Sharma',
    photo: '/aarav.png',
    rollNumber: '08',
    admissionNumber: 'ADM-2023-8A08',
    classGrade: 'Class 8',
    section: 'A',
    parentName: 'Sunita Sharma',
    parentPhone: '+91 98765 43210',
    busRoute: 'Route #4 (Saket - Hauz Khas)',
    busStop: 'Saket Metro Station Gate 2',
    attendancePct: 98,
    attendanceStreak: 14,
    homeworkCompletionPct: 94,
    overallTerm3Average: 92,
    growthTrendPct: 14,
    participationLevel: 'High',
    behaviourStatus: 'Exemplary',
    status: 'Healthy',
    storySnippet: 'High achiever in Mathematics, top 10% class performer, ready for Olympiad challenge set.',
  },
  {
    id: 'std-002',
    name: 'Priya Patel',
    photo: '/priya.png',
    rollNumber: '14',
    admissionNumber: 'ADM-2023-8A14',
    classGrade: 'Class 8',
    section: 'A',
    parentName: 'Amit Patel',
    parentPhone: '+91 98765 43211',
    busRoute: 'Route #4 (Saket - Hauz Khas)',
    busStop: 'Malviya Nagar Corner',
    attendancePct: 98,
    attendanceStreak: 12,
    homeworkCompletionPct: 62,
    overallTerm3Average: 78,
    growthTrendPct: -8,
    participationLevel: 'Medium',
    behaviourStatus: 'Needs Attention',
    status: 'Needs Attention',
    storySnippet: 'Homework completion dropped by 30% over 14 days. Pinned on Support Radar for homeroom check-in.',
  },
  {
    id: 'std-003',
    name: 'Kabir Khan',
    photo: '/rohan.png',
    rollNumber: '19',
    admissionNumber: 'ADM-2023-8A19',
    classGrade: 'Class 8',
    section: 'A',
    parentName: 'Reena Khan',
    parentPhone: '+91 98765 43212',
    busRoute: 'Route #2 (Vasant Kunj)',
    busStop: 'Vasant Kunj Sector C Block 9',
    attendancePct: 98,
    attendanceStreak: 10,
    homeworkCompletionPct: 92,
    overallTerm3Average: 82,
    growthTrendPct: 4,
    participationLevel: 'Low',
    behaviourStatus: 'Good',
    status: 'Worth Watching',
    storySnippet: 'Consistent homework submitter with 98% attendance, but quiet in classroom discussions.',
  },
  {
    id: 'std-004',
    name: 'Ananya Gupta',
    photo: '/ananya.png',
    rollNumber: '02',
    admissionNumber: 'ADM-2023-8A02',
    classGrade: 'Class 8',
    section: 'A',
    parentName: 'Sanjay Gupta',
    parentPhone: '+91 98765 43213',
    busRoute: 'Route #1 (South Ext)',
    busStop: 'South Ext Part 2 Market',
    attendancePct: 99,
    attendanceStreak: 22,
    homeworkCompletionPct: 100,
    overallTerm3Average: 96,
    growthTrendPct: 12,
    participationLevel: 'High',
    behaviourStatus: 'Exemplary',
    status: 'Healthy',
    storySnippet: 'Olympiad candidate with 100% homework submission and 96% overall average.',
  },
  {
    id: 'std-005',
    name: 'Meera Joshi',
    photo: '/kabir.png',
    rollNumber: '11',
    admissionNumber: 'ADM-2023-8A11',
    classGrade: 'Class 8',
    section: 'A',
    parentName: 'Vikas Joshi',
    parentPhone: '+91 98765 43214',
    busRoute: 'Route #4 (Saket - Hauz Khas)',
    busStop: 'Hauz Khas Enclave',
    attendancePct: 90,
    attendanceStreak: 4,
    homeworkCompletionPct: 84,
    overallTerm3Average: 81,
    growthTrendPct: 2,
    participationLevel: 'Medium',
    behaviourStatus: 'Good',
    status: 'Worth Watching',
    storySnippet: 'Occasional morning transport delays on Bus Route #4 affecting first period punctuality.',
  },
];
