import { StudentRecord } from './types';

export const STUDENTS_DATA: StudentRecord[] = [
  {
    id: 'b1000000-0000-4000-8000-000000000001',
    name: 'Aarav Sharma',
    photo: '/aarav.png',
    rollNumber: '801',
    admissionNumber: 'ADM-2023-8A01',
    classGrade: 'Class 8',
    section: 'A',
    parentName: 'Sunita Sharma',
    parentPhone: '+91 98765 10001',
    busRoute: 'Route #4 (Saket - Hauz Khas)',
    busStop: 'Saket Metro Station Gate 2',
    attendancePct: 100,
    attendanceStreak: 14,
    homeworkCompletionPct: 94,
    overallTerm3Average: 92,
    growthTrendPct: 14,
    participationLevel: 'High',
    behaviourStatus: 'Exemplary',
    status: 'Healthy',
    storySnippet: 'High achiever in Mathematics, top 10% class performer, ready for Olympiad challenge set.',
  },
  {
    id: 'b1000000-0000-4000-8000-000000000002',
    name: 'Priya Patel',
    photo: '/priya.png',
    rollNumber: '802',
    admissionNumber: 'ADM-2023-8A02',
    classGrade: 'Class 8',
    section: 'A',
    parentName: 'Rajesh Patel',
    parentPhone: '+91 98765 10002',
    busRoute: 'Route #4 (Saket - Hauz Khas)',
    busStop: 'Malviya Nagar Corner',
    attendancePct: 90,
    attendanceStreak: 12,
    homeworkCompletionPct: 62,
    overallTerm3Average: 78,
    growthTrendPct: -8,
    participationLevel: 'Medium',
    behaviourStatus: 'Needs Attention',
    status: 'Needs Attention',
    storySnippet: 'Homework completion dropped by 30% over 14 days. Pinned on Support Radar for homeroom check-in.',
  },
  {
    id: 'b1000000-0000-4000-8000-000000000003',
    name: 'Rohan Singh',
    photo: '/rohan.png',
    rollNumber: '803',
    admissionNumber: 'ADM-2023-8A03',
    classGrade: 'Class 8',
    section: 'A',
    parentName: 'Priya Singh',
    parentPhone: '+91 98765 10003',
    busRoute: 'Route #2 (Vasant Kunj)',
    busStop: 'Vasant Kunj Sector C Block 9',
    attendancePct: 95,
    attendanceStreak: 10,
    homeworkCompletionPct: 92,
    overallTerm3Average: 82,
    growthTrendPct: 4,
    participationLevel: 'Low',
    behaviourStatus: 'Good',
    status: 'Worth Watching',
    storySnippet: 'Consistent homework submitter with 95% attendance, but quiet in classroom discussions.',
  },
  {
    id: 'b1000000-0000-4000-8000-000000000004',
    name: 'Ananya Gupta',
    photo: '/ananya.png',
    rollNumber: '804',
    admissionNumber: 'ADM-2023-8A04',
    classGrade: 'Class 8',
    section: 'A',
    parentName: 'Amit Gupta',
    parentPhone: '+91 98765 10004',
    busRoute: 'Route #1 (South Ext)',
    busStop: 'South Ext Part 2 Market',
    attendancePct: 99,
    attendanceStreak: 22,
    homeworkCompletionPct: 100,
    overallTerm3Average: 96,
    growthTrendPct: 12,
    participationLevel: 'High',
    behaviourStatus: 'Exemplary',
    status: 'Healthy',
    storySnippet: 'Olympiad candidate with 100% homework submission and 96% overall average.',
  },
  {
    id: 'b1000000-0000-4000-8000-000000000005',
    name: 'Kabir Khan',
    photo: '/kabir.png',
    rollNumber: '805',
    admissionNumber: 'ADM-2023-8A05',
    classGrade: 'Class 8',
    section: 'A',
    parentName: 'Fatima Khan',
    parentPhone: '+91 98765 10005',
    busRoute: 'Route #4 (Saket - Hauz Khas)',
    busStop: 'Hauz Khas Enclave',
    attendancePct: 90,
    attendanceStreak: 4,
    homeworkCompletionPct: 84,
    overallTerm3Average: 81,
    growthTrendPct: 2,
    participationLevel: 'Medium',
    behaviourStatus: 'Good',
    status: 'Worth Watching',
    storySnippet: 'Occasional morning transport delays on Bus Route #4 affecting first period punctuality.',
  },
];
