import type { TeacherProfile } from '../models/index';

export const DEMO_TEACHERS: TeacherProfile[] = [
  {
    id: 't-101',
    firstName: 'Ananya',
    lastName: 'Sharma',
    displayName: 'Ananya Sharma',
    email: 'ananya.sharma@shikshasetu.edu',
    phone: '9876543201',
    subjects: ['Mathematics', 'Algebra'],
    isClassTeacher: true,
    classTeacherOf: '8A',
    classesTaught: [
      { grade: '8', section: 'A', subject: 'Mathematics' },
      { grade: '8', section: 'B', subject: 'Mathematics' },
      { grade: '10', section: 'A', subject: 'Algebra' },
    ],
    staffRoom: 'Staff Room 201 (Second Floor)',
    officeHours: '02:00 PM - 03:00 PM (Mon, Wed, Fri)',
    dailyPeriodsCount: 5,
  },
  {
    id: 't-102',
    firstName: 'Rajesh',
    lastName: 'Mehra',
    displayName: 'Rajesh Mehra',
    email: 'rajesh.mehra@shikshasetu.edu',
    phone: '9876543202',
    subjects: ['Physics', 'General Science'],
    isClassTeacher: true,
    classTeacherOf: '9A',
    classesTaught: [
      { grade: '9', section: 'A', subject: 'Physics' },
      { grade: '9', section: 'B', subject: 'Physics' },
      { grade: '8', section: 'A', subject: 'General Science' },
    ],
    staffRoom: 'Science Block Staff Room 102',
    officeHours: '01:30 PM - 02:30 PM (Tue, Thu)',
    dailyPeriodsCount: 6,
  },
  {
    id: 't-103',
    firstName: 'Priya',
    lastName: 'Nair',
    displayName: 'Priya Nair',
    email: 'priya.nair@shikshasetu.edu',
    phone: '9876543203',
    subjects: ['English Literature', 'English Grammar'],
    isClassTeacher: true,
    classTeacherOf: '10A',
    classesTaught: [
      { grade: '10', section: 'A', subject: 'English' },
      { grade: '9', section: 'A', subject: 'English' },
      { grade: '7', section: 'A', subject: 'English' },
    ],
    staffRoom: 'Humanities Wing Staff Room 105',
    officeHours: '02:15 PM - 03:15 PM (Mon-Fri)',
    dailyPeriodsCount: 5,
  },
  {
    id: 't-104',
    firstName: 'Sunil',
    lastName: 'Verma',
    displayName: 'Sunil Verma',
    email: 'sunil.verma@shikshasetu.edu',
    phone: '9876543204',
    subjects: ['Chemistry', 'Environmental Science'],
    isClassTeacher: true,
    classTeacherOf: '8B',
    classesTaught: [
      { grade: '8', section: 'B', subject: 'Chemistry' },
      { grade: '9', section: 'B', subject: 'Chemistry' },
      { grade: '10', section: 'B', subject: 'Chemistry' },
    ],
    staffRoom: 'Science Block Staff Room 103',
    officeHours: '02:00 PM - 03:00 PM (Wed)',
    dailyPeriodsCount: 5,
  },
  {
    id: 't-105',
    firstName: 'Kavita',
    lastName: 'Deshmukh',
    displayName: 'Kavita Deshmukh',
    email: 'kavita.d@shikshasetu.edu',
    phone: '9876543205',
    subjects: ['Social Studies', 'History', 'Civics'],
    isClassTeacher: true,
    classTeacherOf: '7A',
    classesTaught: [
      { grade: '7', section: 'A', subject: 'Social Studies' },
      { grade: '7', section: 'B', subject: 'Social Studies' },
      { grade: '6', section: 'A', subject: 'History' },
    ],
    staffRoom: 'Main Building Room 110',
    officeHours: '01:45 PM - 02:45 PM (Mon, Thu)',
    dailyPeriodsCount: 5,
  },
  {
    id: 't-106',
    firstName: 'Amitabh',
    lastName: 'Sen',
    displayName: 'Amitabh Sen',
    email: 'amitabh.sen@shikshasetu.edu',
    phone: '9876543206',
    subjects: ['Computer Science', 'Robotics', 'Coding'],
    isClassTeacher: false,
    classesTaught: [
      { grade: '8', section: 'A', subject: 'Computer Science' },
      { grade: '8', section: 'B', subject: 'Computer Science' },
      { grade: '9', section: 'A', subject: 'Computer Science' },
      { grade: '10', section: 'A', subject: 'Computer Science' },
    ],
    staffRoom: 'IT & AI Lab Staff Room',
    officeHours: '03:00 PM - 04:00 PM (Daily)',
    dailyPeriodsCount: 6,
  },
  {
    id: 't-107',
    firstName: 'Deepa',
    lastName: 'Kulkarni',
    displayName: 'Deepa Kulkarni',
    email: 'deepa.k@shikshasetu.edu',
    phone: '9876543207',
    subjects: ['Hindi', 'Sanskrit'],
    isClassTeacher: true,
    classTeacherOf: '6A',
    classesTaught: [
      { grade: '6', section: 'A', subject: 'Hindi' },
      { grade: '6', section: 'B', subject: 'Hindi' },
      { grade: '7', section: 'A', subject: 'Sanskrit' },
    ],
    staffRoom: 'Language Lab Staff Room 101',
    officeHours: '02:00 PM - 03:00 PM (Mon, Tue)',
    dailyPeriodsCount: 4,
  },
  {
    id: 't-108',
    firstName: 'Vikram',
    lastName: 'Rathore',
    displayName: 'Vikram Rathore',
    email: 'vikram.r@shikshasetu.edu',
    phone: '9876543208',
    subjects: ['Physical Education', 'Sports', 'Cricket Coach'],
    isClassTeacher: false,
    classesTaught: [
      { grade: '6', section: 'A', subject: 'PE' },
      { grade: '7', section: 'A', subject: 'PE' },
      { grade: '8', section: 'A', subject: 'PE' },
      { grade: '9', section: 'A', subject: 'PE' },
      { grade: '10', section: 'A', subject: 'PE' },
    ],
    staffRoom: 'Sports Complex Office',
    officeHours: '07:00 AM - 08:00 AM / 03:30 PM - 04:30 PM',
    dailyPeriodsCount: 6,
  },
  {
    id: 't-109',
    firstName: 'Meenakshi',
    lastName: 'Sundaram',
    displayName: 'Meenakshi Sundaram',
    email: 'meenakshi.s@shikshasetu.edu',
    phone: '9876543209',
    subjects: ['Biology', 'Life Sciences'],
    isClassTeacher: true,
    classTeacherOf: '9B',
    classesTaught: [
      { grade: '9', section: 'B', subject: 'Biology' },
      { grade: '10', section: 'B', subject: 'Biology' },
      { grade: '8', section: 'B', subject: 'Life Sciences' },
    ],
    staffRoom: 'Biology Lab Staff Room 204',
    officeHours: '02:00 PM - 03:00 PM (Tue, Fri)',
    dailyPeriodsCount: 5,
  },
  {
    id: 't-110',
    firstName: 'Rakesh',
    lastName: 'Kapoor',
    displayName: 'Rakesh Kapoor',
    email: 'rakesh.k@shikshasetu.edu',
    phone: '9876543210',
    subjects: ['Geography', 'Economics'],
    isClassTeacher: true,
    classTeacherOf: '7B',
    classesTaught: [
      { grade: '7', section: 'B', subject: 'Geography' },
      { grade: '9', section: 'A', subject: 'Economics' },
      { grade: '10', section: 'A', subject: 'Economics' },
    ],
    staffRoom: 'Humanities Wing Staff Room 106',
    officeHours: '02:30 PM - 03:30 PM (Wed)',
    dailyPeriodsCount: 5,
  },
  {
    id: 't-111',
    firstName: 'Shalini',
    lastName: 'Gupta',
    displayName: 'Shalini Gupta',
    email: 'shalini.g@shikshasetu.edu',
    phone: '9876543211',
    subjects: ['Fine Arts', 'Craft', 'Design'],
    isClassTeacher: false,
    classesTaught: [
      { grade: '6', section: 'A', subject: 'Art' },
      { grade: '7', section: 'A', subject: 'Art' },
      { grade: '8', section: 'A', subject: 'Art' },
    ],
    staffRoom: 'Art Studio Room 302',
    officeHours: '01:30 PM - 02:30 PM (Fri)',
    dailyPeriodsCount: 4,
  },
  {
    id: 't-112',
    firstName: 'Sanjay',
    lastName: 'Joshi',
    displayName: 'Sanjay Joshi',
    email: 'sanjay.j@shikshasetu.edu',
    phone: '9876543212',
    subjects: ['Music', 'Vocal', 'Instruments'],
    isClassTeacher: false,
    classesTaught: [
      { grade: '6', section: 'B', subject: 'Music' },
      { grade: '7', section: 'B', subject: 'Music' },
      { grade: '8', section: 'B', subject: 'Music' },
    ],
    staffRoom: 'Music Room Auditorium Basement',
    officeHours: '02:00 PM - 03:00 PM (Thu)',
    dailyPeriodsCount: 4,
  },
  {
    id: 't-113',
    firstName: 'Neelam',
    lastName: 'Chawla',
    displayName: 'Neelam Chawla',
    email: 'neelam.c@shikshasetu.edu',
    phone: '9876543213',
    subjects: ['Mathematics', 'Geometry'],
    isClassTeacher: true,
    classTeacherOf: '6B',
    classesTaught: [
      { grade: '6', section: 'B', subject: 'Mathematics' },
      { grade: '7', section: 'A', subject: 'Mathematics' },
    ],
    staffRoom: 'Staff Room 202',
    officeHours: '02:00 PM - 03:00 PM (Mon)',
    dailyPeriodsCount: 5,
  },
  {
    id: 't-114',
    firstName: 'Gaurav',
    lastName: 'Tiwari',
    displayName: 'Gaurav Tiwari',
    email: 'gaurav.t@shikshasetu.edu',
    phone: '9876543214',
    subjects: ['French', 'Spanish'],
    isClassTeacher: false,
    classesTaught: [
      { grade: '8', section: 'A', subject: 'French' },
      { grade: '9', section: 'A', subject: 'French' },
    ],
    staffRoom: 'Foreign Language Center',
    officeHours: '02:30 PM - 03:30 PM (Tue)',
    dailyPeriodsCount: 4,
  },
  {
    id: 't-115',
    firstName: 'Sunita',
    lastName: 'Rao',
    displayName: 'Dr. Sunita Rao',
    email: 'principal@shikshasetu.edu',
    phone: '9876543200',
    subjects: ['School Administration', 'Value Education'],
    isClassTeacher: false,
    classesTaught: [
      { grade: '10', section: 'A', subject: 'Value Education' },
    ],
    staffRoom: 'Principal\'s Executive Suite',
    officeHours: '10:00 AM - 12:00 PM (By appointment)',
    dailyPeriodsCount: 2,
  },
];
