'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

export interface ActionPayload {
  id: string;
  type: 'message' | 'intervention_plan' | 'report' | 'export';
  title: string;
  preview: string;
  actions: string[];
  payload?: Record<string, any>;
}

interface ActionModalProps {
  isOpen: boolean;
  onClose: () => void;
  actionObject: ActionPayload | null;
}

export default function SchoolGPTActionModal({ isOpen, onClose, actionObject }: ActionModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !actionObject) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(actionObject.preview);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleWhatsAppShare = () => {
    const encodedText = encodeURIComponent(`*${actionObject.title}*\n\n${actionObject.preview}`);
    window.open(`https://api.whatsapp.com/send?text=${encodedText}`, '_blank');
  };

  const handlePrintPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>${actionObject.title}</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 40px; color: #0f172a; line-height: 1.6; }
            h1 { color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; }
            .preview { background: #f8fafc; border: 1px solid #e2e8f0; padding: 20px; border-radius: 12px; font-family: monospace; white-space: pre-wrap; }
            .footer { margin-top: 40px; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 12px; }
          </style>
        </head>
        <body>
          <h1>ShikshaSetu Official Document: ${actionObject.title}</h1>
          <div class="preview">${actionObject.preview}</div>
          <div class="footer">Generated by SchoolGPT Adaptive AI Operating System • ${new Date().toLocaleDateString()}</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/50 backdrop-blur-sm font-body">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 15 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 15 }}
          className="bg-white rounded-3xl border border-slate-200/90 p-6 sm:p-7 max-w-lg w-full shadow-2xl space-y-5"
        >
          {/* Modal Header */}
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div className="flex items-center gap-2.5">
              <div className="w-9 h-9 rounded-2xl bg-slate-900 text-white font-display text-xs font-black flex items-center justify-center">
                ⚡
              </div>
              <div>
                <h3 className="font-display text-base font-extrabold text-slate-900">
                  {actionObject.title}
                </h3>
                <p className="text-xs font-medium text-slate-500 font-mono">
                  Type: {actionObject.type.toUpperCase()}
                </p>
              </div>
            </div>
            <button
              type="button"
              onClick={onClose}
              className="h-8 w-8 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs transition-all flex items-center justify-center"
            >
              ✕
            </button>
          </div>

          {/* Action Document Preview */}
          <div className="p-4 bg-slate-50 border border-slate-200/80 rounded-2xl space-y-2 text-xs font-mono text-slate-800 leading-relaxed max-h-60 overflow-y-auto whitespace-pre-wrap">
            {actionObject.preview}
          </div>

          {/* Execution Action Triggers */}
          <div className="space-y-2 pt-1">
            <span className="text-[10px] font-mono font-extrabold uppercase tracking-widest text-slate-400 block">
              Choose Action:
            </span>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
              <button
                type="button"
                onClick={handleWhatsAppShare}
                className="px-4 py-2.5 rounded-2xl bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold text-xs shadow-xs transition-all flex items-center justify-center gap-1.5 active:scale-95"
              >
                <span>✉️</span>
                <span>Send WhatsApp</span>
              </button>

              <button
                type="button"
                onClick={handlePrintPDF}
                className="px-4 py-2.5 rounded-2xl bg-slate-900 hover:bg-slate-800 text-white font-extrabold text-xs shadow-xs transition-all flex items-center justify-center gap-1.5 active:scale-95"
              >
                <span>📥</span>
                <span>Print / PDF</span>
              </button>

              <button
                type="button"
                onClick={handleCopy}
                className="px-4 py-2.5 rounded-2xl bg-slate-100 hover:bg-slate-200 text-slate-800 font-extrabold text-xs border border-slate-200/80 transition-all flex items-center justify-center gap-1.5 active:scale-95"
              >
                <span>{copied ? '✓' : '📋'}</span>
                <span>{copied ? 'Copied!' : 'Copy Text'}</span>
              </button>
            </div>
          </div>

          {/* Footer Note */}
          <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-[11px] font-medium text-slate-400">
            <span>ShikshaSetu Assistant</span>
            <button
              type="button"
              onClick={onClose}
              className="font-bold text-slate-600 hover:text-slate-900"
            >
              Close
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
